[package]
name = "day22"
version = "0.1.0"
authors = ["Winston Weinert <winston@ml1.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.1"
